## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.random.randint(0, 11, size=10)
print("Исходный массив:", arr)

arr = np.where((arr >= 3) & (arr <= 8), -arr, arr)

print("Массив после изменения знаков:", arr)


Исходный массив: [ 7  1  4 10  3  5  1  3  9  5]
Массив после изменения знаков: [-7  1 -4 10 -3 -5  1 -3  9 -5]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
import numpy as np

arr = np.random.randint(0, 11, size=10)
print("Исходный массив:", arr)

max_index = np.argmax(arr)

arr[max_index] = 0

print("Массив после замены максимального элемента на 0:", arr)


Исходный массив: [ 1  6 10  9  7  4  0  4  6  7]
Массив после замены максимального элемента на 0: [1 6 0 9 7 4 0 4 6 7]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
from itertools import product

# Пример произвольного двумерного массива (строки могут быть разной длины)
arr = [
    [1, 2],
    [3, 4, 5],
    [6, 7]
]

cartesian = np.array(list(product(*arr)))

print("Исходный массив:")
for row in arr:
    print(row)

print("\nПрямое произведение:")
print(cartesian)

Исходный массив:
[1, 2]
[3, 4, 5]
[6, 7]

Прямое произведение:
[[1 3 6]
 [1 3 7]
 [1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 3 6]
 [2 3 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [11]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 2, 4],
    [4, 5, 6],
    [5, 6, 7],
    [7, 8, 9],
    [2, 4, 6],
    [6, 5, 4]
])

B = np.array([
    [1, 2],
    [5, 6]
])

matching_rows = {}

for b_row in B:
    mask = np.array([all(item in row for item in b_row) for row in A])
    matching_rows[tuple(int(x) for x in b_row)] = A[mask]

for b_row, rows in matching_rows.items():
    print(f"Строка B {b_row} встречается в строках A:\n{rows}\n")


Строка B (1, 2) встречается в строках A:
[[1 2 3]
 [3 2 1]
 [1 2 4]]

Строка B (5, 6) встречается в строках A:
[[4 5 6]
 [5 6 7]
 [6 5 4]]



**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [12]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [3, 3, 3],
    [2, 2, 3],
    [4, 5, 6],
    [1, 1, 2],
    [7, 8, 9],
    [0, 0, 0],
    [1, 2, 1],
    [3, 4, 5],
    [6, 6, 7]
])

mask = np.apply_along_axis(lambda row: len(np.unique(row)) > 1, 1, arr)

filtered_arr = arr[mask]

print("Строки с неравными значениями:\n", filtered_arr)


Строки с неравными значениями:
 [[1 2 3]
 [2 2 3]
 [4 5 6]
 [1 1 2]
 [7 8 9]
 [1 2 1]
 [3 4 5]
 [6 6 7]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [13]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

unique_rows = np.unique(arr, axis=0)

print("Уникальные строки:\n", unique_rows)


Уникальные строки:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [15]:
# Чистый Python
X = [
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
]

n = min(len(X), len(X[0]))
diag = [X[i][i] for i in range(n) if X[i][i] != 0]

prod = 1
for val in diag:
    prod *= val

print(prod)

# NumPy

import numpy as np

X = np.array([
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
])

diag = np.diagonal(X)  
prod = np.prod(diag[diag != 0])
print(prod)


3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [16]:
# Чистый Python

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

def same_multiset(a, b):
    unique_elements = set(a + b)
    return all(a.count(e) == b.count(e) for e in unique_elements)

result = same_multiset(x, y)
print(result)

# NumPy

import numpy as np

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

ux, cx = np.unique(x, return_counts=True)
uy, cy = np.unique(y, return_counts=True)

result = np.array_equal(ux, uy) and np.array_equal(cx, cy)
print(result) 



True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [17]:
# Чистый Python

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

values_after_zero = [x[i] for i in range(1, len(x)) if x[i-1] == 0]

max_val = max(values_after_zero)
print(max_val)

# NumPy

import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mask = x[:-1] == 0
max_val = np.max(x[1:][mask])
print(max_val) 



5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [18]:
# Чистый Python

x = [2, 2, 2, 3, 3, 3, 5]

values = []
counts = []

current = x[0]
count = 1

for i in range(1, len(x)):
    if x[i] == current:
        count += 1
    else:
        values.append(current)
        counts.append(count)
        current = x[i]
        count = 1

values.append(current)
counts.append(count)

print(values)  
print(counts)

# NumPy

import numpy as np

x = np.array([2, 2, 2, 3, 3, 3, 5])

change_indices = np.where(np.diff(x) != 0)[0] + 1

counts = np.diff(np.concatenate(([0], change_indices, [len(x)])))
values = x[np.concatenate(([0], change_indices))]

print(values) 
print(counts) 



[2, 3, 5]
[3, 3, 1]
[2 3 5]
[3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [19]:
# Чистый Python

import math

X = [[1, 2], [3, 4], [5, 6]]
Y = [[1, 0], [0, 1]]

dist_matrix = []

for x in X:
    row = []
    for y in Y:
        dist = math.sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))
        row.append(dist)
    dist_matrix.append(row)

for row in dist_matrix:
    print(row)

# NumPy

import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[1, 0], [0, 1]])

diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
dist_matrix = np.sqrt(np.sum(diff**2, axis=2))

print(dist_matrix)



[2.0, 1.4142135623730951]
[4.47213595499958, 4.242640687119285]
[7.211102550927978, 7.0710678118654755]
[[2.         1.41421356]
 [4.47213595 4.24264069]
 [7.21110255 7.07106781]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [20]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [21]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

crunchie_calories = 60

average_calories = np.mean(calorie_stats)

calorie_difference = average_calories - crunchie_calories

print("Среднее количество калорий у конкурентов:", average_calories)
print("Насколько выше калорийность у конкурентов:", calorie_difference)


Среднее количество калорий у конкурентов: 106.88311688311688
Насколько выше калорийность у конкурентов: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [22]:
import numpy as np

calorie_stats_sorted = np.sort(calorie_stats)

print("Отсортированные калории конкурентов:")
print(calorie_stats_sorted)


Отсортированные калории конкурентов:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [24]:
median_calories = np.median(calorie_stats)

print("Медиана калорий конкурентов:", median_calories)

Медиана калорий конкурентов: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [25]:
import numpy as np

percentiles = np.arange(0, 101, 1) 
percentile_values = np.percentile(calorie_stats, percentiles)

nth_percentile = percentiles[np.where(percentile_values > 60)[0][0]]

print("Наименьший процентиль, превышающий 60 калорий:", nth_percentile)


Наименьший процентиль, превышающий 60 калорий: 4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [26]:
import numpy as np

more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100
print(more_calories)


96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [27]:
import numpy as np

calorie_std = np.std(calorie_stats)
print(calorie_std)


19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# CrunchieMunchies является наименее калорийным выбором среди большинства конкурентов, 
# что можно использовать в маркетинговых материалах, 
# акцентируя внимание на пользе и лёгкости продукта для здоровья потребителей.